FROM node:16
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install
ENV REACT_APP_BACKEND_LOCATION=https://logic.tallypeer.com
ENV REACT_APP_API=api/v1
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "start", "--env=production" ]