version: "3.9"
services:
  react:
    environment:
      REACT_APP_BACKEND_LOCATION: http://localhost:3001
      REACT_APP_API: api/v1

    container_name: "dework_frontend"
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
