version: "3.9"
services:
  react:
    image: registry.digitalocean.com/dework/react:latest
    environment:
      VIRTUAL_HOST: tallypeer.com
      LETSENCRYPT_HOST: tallypeer.com

    container_name: "dework_frontend"

networks:
  default:
    external:
      name: proxy