version: "3.9"
services:
  react:
    image: registry.digitalocean.com/dework/react_staging:latest
    environment:
      VIRTUAL_HOST: staging.tallypeer.com
      LETSENCRYPT_HOST: staging.tallypeer.com

    container_name: "dework_frontend_staging"

networks:
  default:
    external:
      name: proxy